CREATE TABLE unit(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name CHAR(64)
);

CREATE TABLE type(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name CHAR(16)
	unit_id INTEGER NOT NULL,
	FOREIGN KEY(unit_id) REFERENCES unit(id)
);

CREATE TABLE company(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name CHAR(255) NOT NULL,
	type_id INTEGER NOT NULL,
	price DOUBLE NOT NULL DEFAULT 0,
	cnt INTEGER NOT NULL DEFAULT 0,
	conversion_rate DOUBLE,
	CTR DOUBLE
	FOREIGN KEY(type_id) REFERENCES type(id)
);