CREATE TABLE monetize(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    date DATE NOT NULL,
    profit_sells DOUBLE NOT NULL DEFAULT 0,
    profit_advs DOUBLE NOT NULL DEFAULT 0,
    DAU INTEGER NOT NULL DEFAULT 0,
    MAU INTEGER NOT NULL DEFAULT 0,
    LAU INTEGER NOT NULL DEFAULT 0,
    new_users INTEGER NOT NULL DEFAULT 0,
    PAU INTEGER NOT NULL DEFAULT 0,
    network_posts INTEGER NOT NULL DEFAULT 0,
    avg_session_time DOUBLE NOT NULL DEFAULT 0,
    avg_session_count DOUBLE NOT NULL DEFAULT 0
);